#!/usr/bin/env bash
# Iron Ledger — production prep: secrets + build + dependency sync + boot-verify.
#
# Does NOT start the server (so it never fights a running instance or needs sudo);
# it gets everything PROD-ready and prints the exact start command. Safe to re-run.
#
#   ./run.sh
#
# Steps:
#   1. Verify prereqs (uv, node/npm).
#   2. Ensure server/.env exists with a strong WT_SECRET (generate if missing).
#   3. Ensure a REAL WT_INVITE_CODE — prompt for one if it's still the placeholder
#      (signup returns 503 until this is set).
#   4. uv sync (server) + npm install + npm run build (client).
#   5. Boot-verify: import the FastAPI app so a broken build fails HERE, not at start.
#   6. Print the start command (./scripts/serve.sh) + tunnel + backup next steps.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER_DIR="$REPO_DIR/server"
CLIENT_DIR="$REPO_DIR/client"
ENV_FILE="$SERVER_DIR/.env"

info() { printf '\033[1;34m[run]\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m[run]\033[0m %s\n' "$1"; }
err()  { printf '\033[1;31m[run]\033[0m %s\n' "$1" >&2; }

gen_secret() { python3 -c "import secrets; print(secrets.token_urlsafe(48))"; }

# Read KEY=value from server/.env (env var wins, else .env, else the given default).
env_or() { # env_or VARNAME DEFAULT
  local cur="${!1:-}"
  if [ -z "$cur" ] && [ -f "$ENV_FILE" ]; then
    cur="$(grep -E "^$1=.+" "$ENV_FILE" | head -n1 | cut -d= -f2- || true)"
  fi
  printf '%s' "${cur:-$2}"
}

# ---- 1. prerequisites ---------------------------------------------------------
for tool in uv node npm python3; do
  command -v "$tool" >/dev/null 2>&1 || { err "$tool not found. Run ./setup.sh first (installs uv/node deps)."; exit 1; }
done
info "Repo: $REPO_DIR"

# ---- 2. WT_SECRET -------------------------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
  info "No server/.env — generating one with a random WT_SECRET."
  ( umask 077  # born 0600 so the secret is never world-readable
    cat > "$ENV_FILE" <<EOF
# Generated by run.sh. Gitignored. Do not commit.
WT_SECRET=$(gen_secret)
WT_INVITE_CODE=change-me-$(gen_secret | cut -c1-8)
# OPTIONAL: where the event log lives (default: <repo>/data). Point at the NAS to
# keep data off the deploy box, e.g. WT_DATA_DIR=/mnt/.../iron-ledger-data
# WT_DATA_DIR=
# OPTIONAL: single prod listen host/port (server serves API + client on one origin).
# WT_HOST=127.0.0.1
# WT_PORT=8000
EOF
  )
fi
grep -Eq '^WT_SECRET=.+' "$ENV_FILE" || { err "WT_SECRET missing/empty in $ENV_FILE."; exit 1; }
info "WT_SECRET present."

# ---- 3. real WT_INVITE_CODE ---------------------------------------------------
# Acceptable = >=8 chars and not the setup.sh placeholder. Re-validated on every
# run so a short/placeholder existing value is corrected too (not just empty).
invite_ok() { [ "${#1}" -ge 8 ] && [[ "$1" != change-me* ]]; }

current_invite=""
if grep -qE '^WT_INVITE_CODE=' "$ENV_FILE"; then
  current_invite="$(grep -E '^WT_INVITE_CODE=' "$ENV_FILE" | head -n1)"
  current_invite="${current_invite#WT_INVITE_CODE=}"
fi

if invite_ok "$current_invite"; then
  info "WT_INVITE_CODE already set — leaving it untouched."
else
  warn "WT_INVITE_CODE is unset/placeholder/too-short — signup is DISABLED (503) until set."
  while :; do
    printf '\033[1;34m[run]\033[0m Enter a real invite code (>=8 chars, hand to trusted users): '
    read -r new_invite
    invite_ok "$new_invite" && break
    warn "Too short (<8) or still a placeholder — try again."
  done
  # Rewrite WT_INVITE_CODE atomically (temp + fsync + os.replace) so an interrupted
  # write can never truncate the file and lose WT_SECRET; force 0600 on the new file
  # regardless of the old mode. Pass the code via env (not argv -> not visible in ps).
  WT_NEW_INVITE="$new_invite" python3 - "$ENV_FILE" <<'PY'
import os, sys, tempfile
path = sys.argv[1]
code = os.environ["WT_NEW_INVITE"]
with open(path) as f:
    lines = f.read().splitlines()
out, found = [], False
for ln in lines:
    if ln.startswith("WT_INVITE_CODE="):
        out.append("WT_INVITE_CODE=" + code); found = True
    else:
        out.append(ln)
if not found:
    out.append("WT_INVITE_CODE=" + code)
data = ("\n".join(out) + "\n").encode()
fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path) or ".", prefix=".env.")
try:
    os.fchmod(fd, 0o600)
    with os.fdopen(fd, "wb") as f:
        f.write(data); f.flush(); os.fsync(f.fileno())
    os.replace(tmp, path)  # atomic on the same filesystem
except BaseException:
    try:
        os.unlink(tmp)
    except OSError:
        pass
    raise
PY
  info "WT_INVITE_CODE set."
fi

# ---- 4. build -----------------------------------------------------------------
# Guard: npm's node_modules/.bin shims need symlinks. On a no-symlink fs (Windows
# mount / synced / NAS folder) the build dies with a cryptic vite "Cannot find
# module .../node_modules/dist/node/cli.js". Fail fast with a real fix instead.
probe="$CLIENT_DIR/.symlink_probe_$$"
if ln -s . "$probe" 2>/dev/null; then
  rm -f "$probe"
else
  rm -f "$probe" 2>/dev/null || true
  err "Filesystem at $CLIENT_DIR has no symlink support — npm/vite will break."
  err "Clone onto a NATIVE Linux filesystem and run there:"
  err "  git clone https://github.com/SmitRajguru/iron-ledger.git ~/iron_ledger"
  err "  cd ~/iron_ledger && ./run.sh   (event log can still live on the NAS via WT_DATA_DIR)"
  exit 1
fi

# A copied .venv (e.g. off a NAS) has an arch-specific python that can't exec here
# ("exec format error"); uv sync would fail querying it. Drop a broken one so uv rebuilds.
if [ -e "$SERVER_DIR/.venv/bin/python3" ] && ! "$SERVER_DIR/.venv/bin/python3" -c "" >/dev/null 2>&1; then
  warn "server/.venv looks broken (copied across machines?) — removing so uv rebuilds it."
  rm -rf "$SERVER_DIR/.venv"
fi

# A uv.lock pinned to a PRIVATE index (corporate mirror) is unreachable off that
# network -> uv sync fails with a DNS error. Drop a non-public lock so uv re-resolves
# from this box's default index (public PyPI); pyproject deps are loose, so it's safe.
LOCK="$SERVER_DIR/uv.lock"
if [ -f "$LOCK" ] && grep -q 'registry = "' "$LOCK" && grep 'registry = "' "$LOCK" | grep -vq 'pypi\.org'; then
  reg="$(grep -m1 'registry = "' "$LOCK" | sed 's/.*registry = "\([^"]*\)".*/\1/')"
  warn "uv.lock pinned to a non-public index ($reg) — removing so uv resolves from public PyPI."
  rm -f "$LOCK"
fi

info "Syncing server deps (uv sync)…"
( cd "$SERVER_DIR" && uv sync )
info "Building client (npm install + npm run build)…"
( cd "$CLIENT_DIR" && npm install && npm run build )
[ -f "$CLIENT_DIR/dist/index.html" ] || { err "client build produced no dist/index.html."; exit 1; }
info "Client build present."

# Gate: every dependency must resolve from a PUBLIC registry (no private mirror
# leaked into the freshly-synced lockfiles). Fails loud rather than shipping it.
info "Checking dependency sources are public…"
bash "$REPO_DIR/scripts/check-public-deps.sh"

# ---- 5. boot-verify + data dir ------------------------------------------------
info "Boot-verify: importing the FastAPI app…"
( cd "$SERVER_DIR" && uv run python -c "import app.main; print('  app imports OK')" )

# Resolve the event-log location (WT_DATA_DIR from .env, else <repo>/data) and make
# sure it exists + is writable. WT_DATA_DIR can point at the NAS so data persists
# off the (native) deploy box — but then the NAS must be mounted before start.
data_dir=""
if grep -qE '^WT_DATA_DIR=.+' "$ENV_FILE"; then
  data_dir="$(grep -E '^WT_DATA_DIR=' "$ENV_FILE" | head -n1)"
  data_dir="${data_dir#WT_DATA_DIR=}"
fi
data_dir="${data_dir:-$REPO_DIR/data}"
if mkdir -p "$data_dir" 2>/dev/null && [ -w "$data_dir" ]; then
  info "Data dir OK: $data_dir"
else
  warn "Data dir not writable: $data_dir"
  warn "  (If on the NAS, mount it before starting the server.)"
fi

# Prod is a SINGLE port (the API server also serves the built client). Resolve
# host/port (env var > server/.env > default) for the start command below.
HOST="$(env_or WT_HOST 127.0.0.1)"
PORT="$(env_or WT_PORT 8000)"
info "Server will listen on $HOST:$PORT (set WT_HOST/WT_PORT in server/.env to change)."

# ---- 6. next steps ------------------------------------------------------------
cat <<EOF

$(info "Prod prep complete. The server is NOT started — start it when you want:")

  Start (foreground; Ctrl-C to stop):
    ./scripts/serve.sh
    # or directly:
    cd "$SERVER_DIR" && uv run uvicorn app.main:app --host $HOST --port $PORT --workers 1

  Then:
    • Reach it at  http://$HOST:$PORT  (one origin: API + client). For a public URL,
      point your Cloudflare tunnel ingress at it (see deploy/cloudflared-config.yml).
    • Event log lives at: $data_dir
    • Back up anytime:  scripts/backup.sh   (restore: scripts/backup.sh --restore <tarball>)
EOF
